jcalazan/ansible-django-stack

roles/nginx/templates/youtubeadl.j2
SSL v3 has a widely known vulnerability in the protocol. For security reasons, [it should be disabled](http://disablessl3.com/#nginx).
While we're at it, remove the only tabs remaining in the NGINX config file.
=> Disable SSL v3, close POODLE vulnerability

roles/web/vars/main.yml
Unfortunately, `default(omit)` "is a hack that applies only to the arguments passed to a module." (https://github.com/ansible/ansible/issues/14130)
This pattern creates problems for the postactivate script as well as any usage of `environment: "{{ django_environment }}"` as any omitted variables will be set to `"__omit_place_holder__<token>"`
This pattern doesn't currently create any problems since all the key Django environment variables are defined. However, if one were to copy this pattern (say, for creating additional optional Django environment vars) or rely on any omitted environment variables to not be set, you'd have an unexpected result.
----
```bash
vagrant up
vagrant ssh
sudo cat /webapps/youtubeadl/bin/postactivate
#!/bin/sh
export …
```
=> Remove erroneous usage of default(omit)

README.md
Was just updating a new server and saw that I accidentally put the wrong path in the README for `server_user_password`. This fixes the issue.
=> Fix typo in README referring to server_user_password location.

README.md, Vagrantfile, dbservers.yml, roles/base/defaults/main.yml, roles/base/tasks/main.yml, roles/celery/tasks/copy_scripts.yml, roles/celery/tasks/main.yml, roles/celery/tasks/setup_supervisor.yml, roles/db/tasks/main.yml, roles/rabbitmq/tasks/main.yml, roles/web/defaults/main.yml, roles/web/tasks/install_additional_packages.yml, roles/web/tasks/setup_supervisor.yml, roles/web/tasks/setup_virtualenv.yml, vagrant.yml, webservers.yml
Please review and merge this collection of fixes, some of which are motivated by issues I encountered just trying to run the stack out-of-the-box.
A notable change however is making [Felix Krull's New Python Versions PPA](https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes/) optional and disabled by default, because of the disclaimer in the PPA description against using it in a production environment, and because Python 3.4 is already available from the main Ubuntu 14.04 repository. (However, this change actually extends support for using this PPA as well by allowing Python 3.6 to be installed, just by overriding two variables.) These changes were tested with the application using Python 2.7 and Python 3.4 from the main Ubuntu 14.04 repository, as well as Python 3.5 and Python 3.6 …
=> Fixes for package installation and service control, and minor cleanups

Vagrantfile
With the latest version of Vagrant (1.9.3), I have successfully used the playbook for deploying a Django app. Fixes #64.
=> Vagrantfile to 16.04

roles/web/templates/virtualenv_postactivate.j2
python3 does not support iteritems() on dict. I was unable to do six.iteritems(django_environment) but was unable to do it in J2 template. This allows playbook to be played with both python2 and python3.
=> Use items() to support both python2 and python3

roles/security/tasks/create_non_root_sudo_user.yml, roles/web/tasks/set_file_permissions.yml, roles/web/tasks/setup_django_app.yml, roles/web/tasks/setup_git_repo.yml
In parts of the repo we have `changed_when: False` to make sure the test suite doesn't throw an error in its idempotence test. However, if `changed_when` is set to false, `notify` will never run. 
The issue I was experiencing is that the `restart application` handler is being called from `set_file_premissions.yml`, so running tasks with the `deploy` tag wasn't triggering Supervisor to restart the Gunicorn app.
This PR removes any `notify` directive from tasks that have `changed_when: False`. It also moves the `restart application` handler to run after changes occur to the git repo or collectstatic tasks (which makes more sense anyway because these are actual signs that the app needs restarting).
=> Remove notify from tasks where changed_when is False; add restart application handler to changes in git repo and collectstatic command.

roles/db/tasks/main.yml
This adds the `enctyped=yes` directive that is now required for PostgreSQL 10. It should be backwards compatible for any Postgres instance <= 9.2 and probably earlier. 
Per the [release notes](https://www.postgresql.org/docs/devel/static/release-10.html): 
> Remove the ability to store unencrypted passwords on the server (Heikki Linnakangas)
> The password_encryption server parameter no longer supports off or plain. The UNENCRYPTED option is no longer supported in CREATE/ALTER USER ... PASSSWORD. Similarly, the --unencrypted option has been removed from createuser. Unencrypted passwords migrated from older versions will be stored encrypted in this release. The default setting for password_encryption is still md5.
=> Encrypt database user password to support PostgreSQL 10.

roles/avahi/tasks/main.yml, roles/base/tasks/main.yml, roles/db/tasks/main.yml, roles/memcached/tasks/main.yml, roles/nginx/tasks/main.yml, roles/rabbitmq/tasks/main.yml, roles/security/tasks/setup_fail2ban.yml, roles/security/tasks/setup_unattended_upgrades.yml, roles/security/tasks/setup_uncomplicated_firewall.yml, roles/web/tasks/install_additional_packages.yml
`state=present` has been the preferred syntax [since at least Ansible version 2.3](https://docs.ansible.com/ansible/2.3/apt_module.html).
From what I can tell, `state=present` _should_ be supported in `apt` for Ansible 2.2 as well (although, is that version still officially supported by this project?)
From [2.2 docs](https://media.readthedocs.org/pdf/ansible/latest/ansible.pdf):
> The `state`parameter is optional to a lot of modules.  Whether `state=present` or `state=absent`, it’s always best to leave that parameter in your playbooks to make it clear, especially as some modules support additional states.
As of version 2.5, it's officially deprecated (to be removed in version 2.9).
=> Use state=present (state=installed is deprecated)

roles/base/tasks/main.yml, roles/db/tasks/main.yml, roles/rabbitmq/tasks/main.yml, roles/web/tasks/install_additional_packages.yml, roles/web/tasks/setup_virtualenv.yml
This behavior was [deprecated in Ansible 2.7](https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.7.html#using-a-loop-on-a-package-module-via-squash-actions).
The behavior we use here instead has been available since Ansible 2.3.
This resolves the deprecation warnings in the [most recent build](https://travis-ci.org/jcalazan/ansible-django-stack/builds/468778606):
> [DEPRECATION WARNING]: Invoking "apt" only once while using a loop via
squash_actions is deprecated. Instead of using a loop to supply multiple items
and specifying `name: "{{ item }}"`, please use `name: ['libcurl4-gnutls-dev',
'gnutls-dev', 'libpq-dev', u"{{ virtualenv_python_version + '-dev' }}"]` and
remove the loop. This feature will be removed in version 2.11. Deprecation
warnings can be disabled by …
=> Don't loop over `apt` or `pip` packages

README.md, Vagrantfile, env_vars/base.yml, roles/web/tasks/setup_git_repo.yml
Currently when using the playbook with a private repository the easiest
way to do it is to copy the private key to the remote server. This is
extremely dangerous. If you lose control of the server then you have lost
control of your source code. In any reasonably busy project tracking down
changes from a malicious user will be very difficult indeed.
The solution is to enable SSH agent forwarding on the remote server (and
the Vagrant box) so when the code is checked out from a git repository,
to which an SSH public key has been added, the request to unlock the key
will be forwarded to the control node where the playbook (or Vagrant)
is being run.
Enabling SSH agent forwarding is simple. Vagrant supports it using the
configuration flag, config.ssh.forward_agent. Ansible also supports it …
=> Checkout code from private git repositories using ssh agent forwarding.

README.md, Vagrantfile, docker/Dockerfile, molecule/default/molecule.yml
- Ubuntu 14.04 is rapidly approaching EOL (April, 2019).
- Python 2 will no longer be supported in one year's time (Jan, 2020)
In this day and age, nobody should really be running infrastructure on
32-bit machines.
Update the README to refer to 18.04 as the default image, with 16.04
supported as well. Python 3 is the default version as well - Python 2
can still be supported, but anybody starting out with this repo likely
will not be deploying Python 2: tune instructions to assume that 18.04
with Python 3 is the default starting point for everyone.
=> Upgrade base image to Bionic Beaver

requirements-dev.txt, requirements.txt
Per Ansible's release cycle, 2.7 is no long receiving "critical bug
fixes." Once 2.10 is released, 2.7 will cease to receive security fixes.
> Ansible maintenance continues for 3 releases. Thus the latest Ansible
> release receives security and general bug fixes when it is first
> released, security and critical bug fixes when the next Ansible
> version is released, and only security fixes once the follow on to
> that version is released.
https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#release-status
-------
Merging this PR as-is will introduce a few new warnings (though the warnings do not break build functionality). Those warnings are addressed in separate PRs:
- https://github.com/jcalazan/ansible-django-stack/pull/131
- …
=> Upgrade Ansible to 2.8

roles/security/vars/main.yml
Without this change, running `vagrant up` (with the `security` role) on
Ansible 2.8 will give warnings:
[WARNING]: The value 22 (type int) in a string field was converted to '22'
(type string). If this does not look like what you expect, quote the entire
value to ensure it does not change.
[WARNING]: The value 80 (type int) in a string field was converted to '80'
(type string). If this does not look like what you expect, quote the entire
value to ensure it does not change.
[WARNING]: The value 443 (type int) in a string field was converted to '443'
(type string). If this does not look like what you expect, quote the entire
value to ensure it does not change.
=> Express ports as strings to silence warning

dbservers.yml, molecule/default/playbook.yml, security.yml, vagrant.yml, webservers.yml
On Ansible 2.8, any step using `apt:` will give a warning:
> [WARNING]: Could not find aptitude. Using apt-get instead
So, do as the warning says and force use of `apt-get`.
This can be done by explicitly adding `force_apt_get: true` beneath each
`apt:` block. However, we can instead enforce this by default at the
module level.
See: https://github.com/ansible/ansible/issues/56832
=> Force `apt-get` use, since aptitude is deprecated

docker/Dockerfile
The vagrant repo has moved from `mitchellh` to the `hashicorp` organization. Update the URL.
=> Load Vagrant keypair from official repo

README.md, requirements.txt
At time of writing, Ansible 2.9 is the [most recent stable release][cycle].
It is maintained with both security and general bug fixes. When 2.10 is released, 2.8 will cease to receive critical bug fixes (only getting security fixes). Get ahead of that process now by upgrading to Ansible 2.9.
No deprecation warnings were observed as part of this upgrade!
[cycle]: https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html
=> Upgrade to Ansible 2.9

README.md, molecule/default/INSTALL.rst
The installed release of molecule (2.22) requires Ansible 2.5 or greater:
> ### Requirements
> ...
> Python 2.7 or Python >= 3.5 with Ansible >= 2.5
https://molecule.readthedocs.io/en/2.22/installation.html
------------------------------------------------------------------------
The next release of Molecule (2.23) will require Ansible 2.7 or greater:
> Supported Ansible versions are now 2.9, 2.8, 2.7
https://github.com/ansible/molecule/blob/master/CHANGELOG.rst
=> Update documentation for supported versions

roles/web/templates/virtualenv_postactivate.j2
Replace double quotes to single quotes in virtualenv_postactivate.j2 in order to reduce bad ecaping of special characters in `postactivate` shell script.
=> Replace double quotes to single quotes in virtualenv_postactivate.j2

README.md, Vagrantfile, docker/Dockerfile, molecule/default/molecule.yml, roles/certbot/defaults/main.yml, roles/certbot/tasks/main.yml
In addition to upgrading vagrant, docker and molecule to use the latest
LTS release there are two other factors which promted the upgrade:
1. certbot-auto cannot be installed on 20.04 LTS as the python-virtual
package is no longer available with the upgrade to python3.
2. The release of certbot 1.9.0 (2020-10-06) deprecates certbot-auto:
https://community.letsencrypt.org/t/certbot-1-9-0-release/135414
The certbot package, provided by Canonical now replaces certbot-auto. It
was tested on a DigitalOcean droplet freshly re-built with 18.04 LTS and
20.04 LTS with no issues.
=> Upgrade to Ubuntu 20.04 LTS (Focal Fossa)

roles/nginx/templates/django_default_project.j2
When a client uses the IP address instead of the domain name Django will
raise an `Invalid HTTP_HOST header` error since the IP address is not
listed in the ALLOWED_HOSTS setting.
This situation occurs most commonly with bots probing the site for security
holes. If you log Django errors using Sentry then a constant stream of these
errors will be reported. At best they are a distraction.
The solution is for nginx to terminate the connection immediately so the
request never reaches Django. This is done simply by matching the host
header with the sites IP address and raising the HTTP error 444 which is
unique to nginx and instructs the server to close the connection immediately.
Nothing is returned to the client so it effectively gets a status code of 0.
The problem and the solution is …
=> Stop invalid host header errors being raised by Django

roles/celery/tasks/setup_supervisor.yml, roles/web/tasks/setup_virtualenv.yml
Hi,
This PR is used for fixing the celery logs directory permissions.
This directory (`celery_log_dir`) is our application log directory:
- `application_log_dir`: https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/defaults/main.yml#L12
- `celery_log_dir`: https://github.com/jcalazan/ansible-django-stack/blob/master/roles/celery/vars/main.yml#L15
But we should set "774" permissions to `application_log_dir`: (https://github.com/jcalazan/ansible-django-stack/blob/master/roles/web/tasks/setup_virtualenv.yml#L46)
So adding "0644" to this directory causes the deployment to fail because the application does not have permission to work with the application log file.
Please help me to review and merge, thanks!
=> Fix the logs directory permissions
